{% set version = "8.6.3" %}

package:
  name: jupyter_client
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter_client/jupyter_client-{{ version }}.tar.gz
  sha256: 35b3a0947c4a6e9d589eb97d7d4cd5e90f910ee73101611f01283732bd6d9419

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-kernel = jupyter_client.kernelapp:main
    - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
    - jupyter-run = jupyter_client.runapp:main

requirements:
  host:
    - pip
    - hatchling >=1.5
    - python {{ python_min }}
  run:
    - importlib-metadata >=4.8.3
    - jupyter_core >=4.12,!=5.0.*
    - python >={{ python_min }}
    - python-dateutil >=2.8.2
    - pyzmq >=23.0
    - tornado >=6.2
    - traitlets >=5.3

test:
  source_files:
    - tests
  requires:
    - coverage
    - ipykernel >=6.14
    - pandoc
    - paramiko
    - pip
    - pytest <8.2
    - pytest-jupyter-client >=0.4.1
    - pytest-timeout
    - python {{ python_min }}
  imports:
    - jupyter_client
  commands:
    - pip check
    - jupyter kernelspec list
    - jupyter run -h
    - coverage run --source=jupyter_client --branch -m pytest -vv --tb=long --color=yes -k "not (signal_kernel_subprocesses or start_parallel_thread_kernels or start_parallel_process_kernels or open_tunnel or load_ips or input_request or tcp_cinfo)"
    - coverage report --show-missing --skip-covered --fail-under=72
  # TODO: downstreams are broken right now
  # downstreams:
  #  - ipywidgets
  #  - jupyter_server

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: jupyter_client contains the reference implementation of the Jupyter protocol.
  dev_url: https://github.com/jupyter/jupyter_client
  doc_url: https://jupyter-client.readthedocs.io/en/stable/
  doc_source_url: https://github.com/jupyter/jupyter_client/tree/master/docs

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - ocefpaf
    - carreau
    - SylvainCorlay
    - bollwyvl
    - davidbrochart
    - blink1073
