{% set version = "5.3.3" %}

package:
  name: jupyter_client
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_client/jupyter_client-{{ version }}.tar.gz
  sha256: f406f214f9daa92be110d5b83d62f3451ffc73d3522db7350f0554683533ab18

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
    - jupyter-run = jupyter_client.runapp:main
    - jupyter-kernel = jupyter_client.kernelapp:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pywin32  # [win]
    - traitlets
    - jupyter_core
    - python-dateutil >=2.1
    - pyzmq >=13
    - tornado >=4.1

test:
  commands:
    - jupyter kernelspec list
    - jupyter run -h
  imports:
    - jupyter_client

about:
  home: http://jupyter.org
  license: BSD 3-clause
  license_file: COPYING.md
  summary: jupyter_client contains the reference implementation of the Jupyter protocol.

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - ocefpaf
    - carreau
    - SylvainCorlay
