{% set version = "7.3.4" %}

package:
  name: jupyter_client
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_client/jupyter_client-{{ version }}.tar.gz
  sha256: aa9a6c32054b290374f95f73bb0cae91455c58dfb84f65c8591912b8f65e6d56

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-kernel = jupyter_client.kernelapp:main
    - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
    - jupyter-run = jupyter_client.runapp:main

requirements:
  host:
    - pip
    - hatchling
    - python >=3.7
  run:
    - entrypoints
    - jupyter_core >=4.9.2
    - nest-asyncio >=1.5.4
    - python >=3.7
    - python-dateutil >=2.8.2
    - pyzmq >=23.0
    - tornado >=6.0
    - traitlets

test:
  requires:
    - async_generator
    - ipykernel
    - ipython
    - mock
    - pip
    - pytest
    - pytest-asyncio
    - pytest-cov
    - pytest-timeout
  imports:
    - jupyter_client
  commands:
    - pip check
    - jupyter kernelspec list
    - jupyter run -h
    - pytest --pyargs jupyter_client --cov jupyter_client --cov-report term-missing:skip-covered --no-cov-on-fail -k "not test_signal_kernel_subprocesses"

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: jupyter_client contains the reference implementation of the Jupyter protocol.
  dev_url: https://github.com/jupyter/jupyter_client
  doc_url: https://jupyter-client.readthedocs.io/en/stable/
  doc_source_url: https://github.com/jupyter/jupyter_client/tree/master/docs

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - ocefpaf
    - carreau
    - SylvainCorlay
    - bollwyvl
    - davidbrochart
    - blink1073
