{% set version = "8.6.1" %}
{% set pytest_args = "-k \"not (signal_kernel_subprocesses or start_parallel_thread_kernels or start_parallel_process_kernels or open_tunnel or load_ips or input_request or tcp_cinfo) \"" %}

package:
  name: jupyter_client
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_client/jupyter_client-{{ version }}.tar.gz
  sha256: e842515e2bab8e19186d89fdfea7abd15e39dd581f94e399f00e2af5a1652d3f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-kernel = jupyter_client.kernelapp:main
    - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
    - jupyter-run = jupyter_client.runapp:main

requirements:
  host:
    - pip
    - hatchling >=1.5
    - python >=3.8
  run:
    - importlib_metadata >=4.8.3
    - jupyter_core >=4.12,!=5.0.*
    - python >=3.8
    - python-dateutil >=2.8.2
    - pyzmq >=23.0
    - tornado >=6.2
    - traitlets >=5.3

test:
  source_files:
    - tests
  requires:
    - coverage
    - ipykernel >=6.14
    - paramiko
    - pip
    - pytest
    - pytest-cov
    - pytest-jupyter-client >=0.4.1
    - pytest-timeout
  imports:
    - jupyter_client
  commands:
    - pip check
    - jupyter kernelspec list
    - jupyter run -h
    - pytest -vv --cov=jupyter_client --cov=branch --cov-report=term-missing:skip-covered --no-cov-on-fail {{ pytest_args }}
  downstreams:
    - ipywidgets
    - jupyter_server

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: jupyter_client contains the reference implementation of the Jupyter protocol.
  dev_url: https://github.com/jupyter/jupyter_client
  doc_url: https://jupyter-client.readthedocs.io/en/stable/
  doc_source_url: https://github.com/jupyter/jupyter_client/tree/master/docs

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - ocefpaf
    - carreau
    - SylvainCorlay
    - bollwyvl
    - davidbrochart
    - blink1073
