# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "8.8.0"
  python_check_max: "3.14"
  pytest_k: not (signal_kernel_subprocesses or start_parallel_thread_kernels or start_parallel_process_kernels or open_tunnel or load_ips or input_request or tcp_cinfo)

package:
  name: jupyter_client
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-client/jupyter_client-${{ version }}.tar.gz
  sha256: d556811419a4f2d96c869af34e854e3f059b7cc2d6d01a9cd9c85c267691be3e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - jupyter-kernel = jupyter_client.kernelapp:main
      - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
      - jupyter-run = jupyter_client.runapp:main

requirements:
  host:
    - pip
    - hatchling >=1.5
    - python ${{ python_min }}.*
  run:
    - jupyter_core >=5.1
    - python >=${{ python_min }}
    - python-dateutil >=2.8.2
    - pyzmq >=25.0
    - tornado >=6.4.1
    - traitlets >=5.3

tests:
  - python:
      imports: jupyter_client
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - files:
      source:
        - tests/
    requirements:
      run:
        - anyio
        - coverage
        - ipykernel >=6.14
        - pandoc
        - paramiko
        - pip
        - pytest >=7
        - pytest-jupyter-client >=0.6.2
        - pytest-timeout
        - python ${{ python_min }}.*
    script:
      - jupyter kernelspec list
      - jupyter run -h
      - coverage run --source=jupyter_client --branch -m pytest -vv --tb=long --color=yes -k "${{ pytest_k }}"
      - coverage report --show-missing --skip-covered --fail-under=72

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: jupyter_client contains the reference implementation of the Jupyter protocol.
  homepage: https://jupyter.org
  repository: https://github.com/jupyter/jupyter_client
  documentation: https://jupyter-client.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - ocefpaf
    - carreau
    - SylvainCorlay
    - bollwyvl
    - davidbrochart
    - blink1073
